[build]
  publish = "public"
  command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "/api-fallback.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/home.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 